// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.github.zeal18.transform.examples.pb.addressbook

@SerialVersionUID(0L)
final case class PhoneNumber(
  number: _root_.scala.Predef.String = "",
  `type`: io.github.zeal18.transform.examples.pb.addressbook.PhoneType =
    io.github.zeal18.transform.examples.pb.addressbook.PhoneType.MOBILE,
)
