name: CI

on:
  pull_request:
  push:
    branches: ['main']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Lint code
        run: sbt check

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17' ]
        scala: [ '2.12.16', '2.13.8' ]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! compile chimneyJS/test chimneyJVM/test
